remote_theme: pages-themes/architect@v0.2.0
show_downloads: true
plugins:
  - jekyll-remote-theme 
repository: Jerit3787/bpn
github:
  jar_url: "https://github.com/Jerit3787/bpn/releases/download/1.1-GUI/SSBPN.V1.1-GUI.jar"
  zip_url: "https://github.com/Jerit3787/bpn/archive/refs/tags/1.1-GUI.zip"