remote_theme: pages-themes/architect@v0.2.0
show_downloads: true
plugins:
  - jekyll-remote-theme 
repository: Jerit3787/bpn
github:
  jar_url: "https://github.com/Jerit3787/bpn/releases/download/v1.2/SSBPN-1.2.jar"
  zip_url: "https://github.com/Jerit3787/bpn/archive/refs/tags/v1.2.zip"
exclude: ["ant/Sistem Semakan Bantuan Prihatin Nasional GUI", "ant/Sistem Semakan Bantuan Prihatin Nasional CLI", "maven/SistemSemakanBantuanPrihatinNasionalGUI"]