# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: 'maven/SistemSemakanBantuanPrihatinNasionalGUI'

    steps:
    - name : Checkout Repo
      uses: actions/checkout@v2
      with:
        fetch-depth: '5'

    - name: Manage Version
      run: |
        git fetch --prune --unshallow --tags
        GIT_SHA="$(git rev-parse --short HEAD)"
        CUR_TAG="$(git tag -l | grep 'dev' | tail -1)"
        echo "SHORT_SHA=$GIT_SHA" >> $GITHUB_ENV
        DATE_CURRENT="$(date +'%Y%m%d')"
        echo "DATE=$DATE_CURRENT" >> $GITHUB_ENV
        if [[ -z $CUR_TAG ]]; then
          echo "OLD_PRE_TAG=NULL" >> $GITHUB_ENV
        else
          echo "OLD_PRE_TAG=$CUR_TAG" >> $GITHUB_ENV
        fi

    - name: Setuping Node latest version
      uses: actions/setup-node@v2.5.0
      with:
        node-version: '16'
        check-latest: true 

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Set Up dependency
      run: npm install

    - name: Test Compile Site & Project GUI
      run: npm run test-build && npm run test-site

    - name: Build Project GUI
      run: npm run build

    - name: Delete Old Pre-Release
      uses: dev-drprasad/delete-tag-and-release@v0.2.0
      with:
        tag_name: ${{ env.OLD_PRE_TAG }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate Prerelease Release Notes
      run: |
        echo '### Disclaimer:' >> ReleaseNotes.md
        echo '***This alpha version is for testing only.***' >> ReleaseNotes.md
        echo 'It is not ready for daily use and we do not guarantee its usability.' >> ReleaseNotes.md
        echo '### The latest five updates are:' >> ReleaseNotes.md
        git log -"5" --format="- %H %s" | sed '/^$/d' >> ReleaseNotes.md

    - name: Publish GitHub Release
      uses: ncipollo/release-action@v1.10.0
      with:
        name: "bpn v1.2-alpha ${{ env.SHORT_SHA }}"
        prerelease: true
        draft: false
        bodyFile: "./ReleaseNotes.md"
        tag: "v1.2-alpha"
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: "./maven/SistemSemakanPrihatinNasionalGUI/target/SSBPN-1.2-Alpha"
        generateReleaseNotes: true

    - name: Clean project
      run: npm run clean
    
