/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.danishstudioproduction.ssbpn.gui;

import javax.swing.JOptionPane;
import utility.Logging;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import mdlaf.*;
import mdlaf.animation.*;
/**
 *
 * @author Danish Hakim
 */
public class mainPanel extends javax.swing.JFrame {

    /**
     * Creates new form mainPanel
     */
    public mainPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        MainPanel = new javax.swing.JTabbedPane();
        maklumatPenggunaPanel = new javax.swing.JPanel();
        namaText = new javax.swing.JLabel();
        namaTextBox = new javax.swing.JTextField();
        noTextBox = new javax.swing.JTextField();
        noText = new javax.swing.JLabel();
        statusPerkahwinanText = new javax.swing.JLabel();
        statusPerkahwinanComboBox = new javax.swing.JComboBox<>();
        pendapatanText = new javax.swing.JLabel();
        pendapatanTextBox = new javax.swing.JTextField();
        bshText = new javax.swing.JLabel();
        bshComboBox = new javax.swing.JComboBox<>();
        lhdnmText = new javax.swing.JLabel();
        lhdnmComboBox = new javax.swing.JComboBox<>();
        semakButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        dataNamaText = new javax.swing.JLabel();
        dataNamaField = new javax.swing.JTextField();
        dataNoField = new javax.swing.JTextField();
        dataNoText = new javax.swing.JLabel();
        dataStatusPerkahwinanField = new javax.swing.JTextField();
        dataStatusPerkahwinanText = new javax.swing.JLabel();
        dataPendapatanField = new javax.swing.JTextField();
        dataPendapatanText = new javax.swing.JLabel();
        dataKategoriField = new javax.swing.JTextField();
        dataKategoriText = new javax.swing.JLabel();
        dataStatusBantuanField = new javax.swing.JTextField();
        dataStatusBantuanText = new javax.swing.JLabel();
        dataSebabField = new javax.swing.JTextField();
        dataSebabText = new javax.swing.JLabel();
        dataJumlahField = new javax.swing.JTextField();
        dataJumlahText = new javax.swing.JLabel();
        dataTindakanText = new javax.swing.JLabel();
        dataTindakanField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selamat Datang ke Sistem Semakan Bantuan Prihatin Nasional (BPN) !");

        maklumatPenggunaPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Maklumat Pengguna"));

        namaText.setText("Nama :");

        namaTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTextBoxActionPerformed(evt);
            }
        });

        noTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTextBoxActionPerformed(evt);
            }
        });

        noText.setText("No. Kad Pengenalan :");

        statusPerkahwinanText.setText("Status Perkahwinan :");

        statusPerkahwinanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bujang", "Sudah Berkahwin" }));

        pendapatanText.setText("Pendapatan (tanpa 'RM') :");

        bshText.setText("Adakah anda merupakan penerima Bantuan Sara Hidup (BSH) :");

        bshComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ya", "Tidak" }));
        bshComboBox.setSelectedIndex(1);

        lhdnmText.setText("Adakah anda berdaftar dengan Lembaga Hasil Dalam Negara (LHDNM) :");

        lhdnmComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ya", "Tidak" }));

        semakButton.setText("Semak");
        semakButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semakButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout maklumatPenggunaPanelLayout = new javax.swing.GroupLayout(maklumatPenggunaPanel);
        maklumatPenggunaPanel.setLayout(maklumatPenggunaPanelLayout);
        maklumatPenggunaPanelLayout.setHorizontalGroup(
            maklumatPenggunaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(namaTextBox)
            .addComponent(noTextBox)
            .addComponent(pendapatanTextBox)
            .addGroup(maklumatPenggunaPanelLayout.createSequentialGroup()
                .addGroup(maklumatPenggunaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaText)
                    .addComponent(noText)
                    .addGroup(maklumatPenggunaPanelLayout.createSequentialGroup()
                        .addComponent(statusPerkahwinanText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusPerkahwinanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pendapatanText)
                    .addComponent(bshText)
                    .addComponent(lhdnmText)
                    .addComponent(bshComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lhdnmComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 115, Short.MAX_VALUE))
            .addComponent(semakButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        maklumatPenggunaPanelLayout.setVerticalGroup(
            maklumatPenggunaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maklumatPenggunaPanelLayout.createSequentialGroup()
                .addComponent(namaText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(maklumatPenggunaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusPerkahwinanText)
                    .addComponent(statusPerkahwinanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pendapatanText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pendapatanTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bshText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bshComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lhdnmText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lhdnmComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(semakButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        MainPanel.addTab("Semakan Baharu", maklumatPenggunaPanel);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Keputusan Semakan"));

        dataNamaText.setText("Nama :");

        dataNamaField.setEditable(false);

        dataNoField.setEditable(false);

        dataNoText.setText("No. Kad Pengenalan :");

        dataStatusPerkahwinanField.setEditable(false);

        dataStatusPerkahwinanText.setText("Status Perkahwinan :");

        dataPendapatanField.setEditable(false);

        dataPendapatanText.setText("Pendapatan :");

        dataKategoriField.setEditable(false);

        dataKategoriText.setText("Kategori Pendapatan :");

        dataStatusBantuanField.setEditable(false);

        dataStatusBantuanText.setText("Status Bantuan :");

        dataSebabField.setEditable(false);

        dataSebabText.setText("Sebab :");

        dataJumlahField.setEditable(false);

        dataJumlahText.setText("Jumlah Bantuan :");

        dataTindakanText.setText("Tindakan Penerima :");

        dataTindakanField.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataNamaField)
                    .addComponent(dataStatusPerkahwinanField)
                    .addComponent(dataPendapatanField)
                    .addComponent(dataKategoriField)
                    .addComponent(dataStatusBantuanField)
                    .addComponent(dataSebabField)
                    .addComponent(dataTindakanField)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataNamaText)
                            .addComponent(dataNoText)
                            .addComponent(dataStatusPerkahwinanText)
                            .addComponent(dataPendapatanText)
                            .addComponent(dataKategoriText)
                            .addComponent(dataStatusBantuanText)
                            .addComponent(dataSebabText)
                            .addComponent(dataJumlahText)
                            .addComponent(dataTindakanText))
                        .addGap(0, 341, Short.MAX_VALUE))
                    .addComponent(dataNoField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dataJumlahField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dataNamaText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataNamaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataNoText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataStatusPerkahwinanText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataStatusPerkahwinanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataPendapatanText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataPendapatanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataKategoriText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataKategoriField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataStatusBantuanText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataStatusBantuanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataSebabText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataSebabField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataJumlahText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataJumlahField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataTindakanText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataTindakanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        MainPanel.addTab("Keputusan Semakan", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Maklumat Pereka Software"));

        jLabel2.setText("Nama :");

        jLabel4.setText("Mohammad Danish Hakim bin Mohd Nasir");

        jButton1.setText("Follow me at Github!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Copyright (c) 2020 Danish Studio Production.");

        jButton2.setText("Follow me at Twitter!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Built using Java.");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Licensed under MIT License.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(435, Short.MAX_VALUE))
        );

        MainPanel.addTab("Maklumat Pereka Software", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MainPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTextBoxActionPerformed

    private void noTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noTextBoxActionPerformed

    private void semakButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semakButtonActionPerformed
        
        //System Checking
        String nameCheckEmpty = namaTextBox.getText();
        String noCheckEmpty = noTextBox.getText();
        String pendapatanCheckEmpty = pendapatanTextBox.getText();
        String empty = "";
        int allowBypass = 1;
        if (nameCheckEmpty.equals(empty)) {
            JOptionPane.showMessageDialog(MainPanel,"Sila penuhkan butiran yang diperlukan.", "Gagal disemak!", JOptionPane.WARNING_MESSAGE);
        }
        else if (noCheckEmpty.equals(empty)) {
            JOptionPane.showMessageDialog(MainPanel,"Sila penuhkan butiran yang diperlukan.", "Gagal disemak!", JOptionPane.WARNING_MESSAGE);
        }
        else if (pendapatanCheckEmpty.equals(empty)) {
            JOptionPane.showMessageDialog(MainPanel,"Sila penuhkan butiran yang diperlukan.", "Gagal disemak!", JOptionPane.WARNING_MESSAGE);
        }
        else {     
            try {
                String noCheckString = noTextBox.getText();
                long noCheck = Long.parseLong(noCheckString);
            }
            catch(NumberFormatException exception) {
                JOptionPane.showMessageDialog(MainPanel,"Sila masukkan nombor pada ruang kad pengenalan dan tiada tanda '-'.", "Gagal disemak", JOptionPane.WARNING_MESSAGE);
                allowBypass = 0;
                Logging.log(exception,true);
            }
            
            try {
                String pendapatanCheckString = pendapatanTextBox.getText();
                int pendapatanCheck = Integer.parseInt(pendapatanCheckString);
            }
            catch(NumberFormatException exception) {
                JOptionPane.showMessageDialog(MainPanel,"Sila masukkan nombor pada ruang pendapatan dan tiada 'RM'.", "Gagal disemak", JOptionPane.WARNING_MESSAGE);
                allowBypass = 0;
            }    
            if (allowBypass == 1) {
                //Initialize variables
            String nama = namaTextBox.getText();
            String noKadPengenalan = noTextBox.getText();
            String statusPerkahwinanObject = (String)statusPerkahwinanComboBox.getSelectedItem();
            String statusPerkahwinan = statusPerkahwinanComboBox.getSelectedItem().toString();
            String pendapatanString = pendapatanTextBox.getText();
            int pendapatan = Integer.parseInt(pendapatanString);
            String pernahBSHObject = (String)bshComboBox.getSelectedItem();
            String pernahBSH = bshComboBox.getSelectedItem().toString();
            String pernahLHDNM = lhdnmComboBox.getSelectedItem().toString();
            String kategoriPendapatan = null;
            int bantuan = 0;
            String bantuanString = null;
        String sebabBantuan = null;
        String bujang = "Bujang";
        String sudahBerkahwin = "Sudah Berkahwin";
        String ya = "Ya";
        String tidak = "Tidak";
        String statusPermohonan = null;
        String statusBantuan = null;
        
        //Sistem Kelayakan
       
        //Perundingan Pertama (Kategori Pendapatan)

        if (pendapatan <= 3000) {
            kategoriPendapatan = "Golongan Below 40 (B40)";
        }
        else if (pendapatan >= 2001 && pendapatan <= 6275) {
            kategoriPendapatan = "Golongan Middle 40 (M40)";
        }
        else {
            kategoriPendapatan = "Golongan Top 20 (T20)";
        }
        
        //Perundingan Kedua (Status Perkahwinan & Jumlah Bantuan)
        if (statusPerkahwinan.equals(bujang)) {
            if (pendapatan <= 1) {
                bantuan = 0;
                sebabBantuan = "Belum bekerja/Tidak bekerja";
            }
            
            else if (pendapatan <= 2000) {
                bantuan = 800;
                sebabBantuan = "Pendapatan dalam lingkungan syarat";
            }
            else if (pendapatan >= 2001 && pendapatan <= 4000) {
                bantuan = 500;
                sebabBantuan = "Pendapatan dalam lingkungan syarat";
            }
            else {
                bantuan = 0;
                sebabBantuan = "Pendapatan dalam lingkungan syarat";
            }
        }
        else if (statusPerkahwinan.equals(sudahBerkahwin)) {
            if (pendapatan <= 4000) {
                bantuan = 1600;
                sebabBantuan = "Pendapatan dalam lingkungan syarat";
            }
            else if (pendapatan >= 4001 && pendapatan <= 8000) {
                bantuan = 1000;
                sebabBantuan = "Pendapatan dalam lingkungan syarat";
            }
            else {
                bantuan = 0;
            }
        }
        else {
        System.out.println("no.failed");
            bantuan = 0;
            JOptionPane.showMessageDialog(MainPanel,"Gagal disemak! Sila semak amount gaji dan status perkahwinan. Masukkan nilai mengikut sistem.");
        }

        //Perundingan Ketiga (Penerima BSH & Pembayar Cukai LHDNM)
        if (pernahBSH.equals(ya)) {
            statusPermohonan = "TIDAK PERLU MEMOHON PERMOHONAN BAHARU";
        }
        else if (pernahLHDNM.equals(ya)) {
            statusPermohonan = "TIDAK PERLU MEMOHON PERMOHONAN BAHARU";
        }
        else {
            statusPermohonan = "PERLU MEMOHON PERMOHONAN BAHARU";
        }
        
        //Perundingan Keempat (Pendapatan)
        if (bantuan == 0) {
            statusBantuan = "Maaf anda tidak layak menerima bantuan!";
            bantuan = 0;
            bantuanString = "RM0";
            pendapatanString = "RM" + pendapatan;
        }
        else {
            statusBantuan = "Tahniah! Anda layak menerima Bantuan Prihatin Nasional (BPN)";
            bantuanString = "RM" + bantuan;
            pendapatanString = "RM" + pendapatan;
        }
        
        //Announce value on next tab
        dataNamaField.setText(nama);
        dataNoField.setText(noKadPengenalan);
        dataStatusPerkahwinanField.setText(statusPerkahwinan);
        dataPendapatanField.setText(pendapatanString);
        dataKategoriField.setText(kategoriPendapatan);
        dataStatusBantuanField.setText(statusBantuan);
        dataSebabField.setText(sebabBantuan);
        dataJumlahField.setText(bantuanString);
        dataTindakanField.setText(statusPermohonan);
        MainPanel.setSelectedIndex(1);
        }
        
            }
    }//GEN-LAST:event_semakButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {

            URI uri= new URI("https://www.twitter.com/Jerit3787");

            java.awt.Desktop.getDesktop().browse(uri);
            System.out.println("Web page opened in browser");

        } catch (Exception e) {

            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

            URI uri= new URI("https://github.com/Jerit3787");

            java.awt.Desktop.getDesktop().browse(uri);
            System.out.println("Web page opened in browser");

        } catch (Exception e) {

            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel (new MaterialLookAndFeel ());
        }
        catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace ();
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane MainPanel;
    private javax.swing.JComboBox<String> bshComboBox;
    private javax.swing.JLabel bshText;
    private javax.swing.JTextField dataJumlahField;
    private javax.swing.JLabel dataJumlahText;
    private javax.swing.JTextField dataKategoriField;
    private javax.swing.JLabel dataKategoriText;
    private javax.swing.JTextField dataNamaField;
    private javax.swing.JLabel dataNamaText;
    private javax.swing.JTextField dataNoField;
    private javax.swing.JLabel dataNoText;
    private javax.swing.JTextField dataPendapatanField;
    private javax.swing.JLabel dataPendapatanText;
    private javax.swing.JTextField dataSebabField;
    private javax.swing.JLabel dataSebabText;
    private javax.swing.JTextField dataStatusBantuanField;
    private javax.swing.JLabel dataStatusBantuanText;
    private javax.swing.JTextField dataStatusPerkahwinanField;
    private javax.swing.JLabel dataStatusPerkahwinanText;
    private javax.swing.JTextField dataTindakanField;
    private javax.swing.JLabel dataTindakanText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> lhdnmComboBox;
    private javax.swing.JLabel lhdnmText;
    private javax.swing.JPanel maklumatPenggunaPanel;
    private javax.swing.JLabel namaText;
    private javax.swing.JTextField namaTextBox;
    private javax.swing.JLabel noText;
    private javax.swing.JTextField noTextBox;
    private javax.swing.JLabel pendapatanText;
    private javax.swing.JTextField pendapatanTextBox;
    private javax.swing.JButton semakButton;
    private javax.swing.JComboBox<String> statusPerkahwinanComboBox;
    private javax.swing.JLabel statusPerkahwinanText;
    // End of variables declaration//GEN-END:variables
}
